<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Manejo de Errores</title>
</head>
<body>
    
<script>

    try {
        console.log("En el try se agrega el codigo a evaluar");
        console.log("Segundo mensaje en el try");
        noExiste;
    } catch (error) {
        console.log("Catch, captura cualquier error, surgido o lanzado en el try");
        console.log(error);
    }finally{
        console.log("El bloque finally se ejecutara al final de un bloque try catch");
    }


    try {
        let numero = "y";

        if (isNaN(numero)) {
            throw new Error("El caracter introducido no es un numero");
        }
        
        cosole.log(numero * numero);
    } catch (error) {
        console.log(`Se produjo el siguiente error: ${error}`)
    }


</script>

</body>
</html>